### ISSUE TITLE
feature request: add  parameters to set minimum and maximum zoom level

### ISSUE THREAD

**Issue by aborruso** [neocarto/geoviz#2]
First of all, thank you for this excellent product.

I would like to have these, because very often a map becomes insubstantial and unreadable at zooms too high or too low.

Thank you

**Comment by neocarto** [comment]
From version 0.2.15, you can set the zoomable parameter to an array of 2 elements. This defines the zoom range. Try for example zoomable: [0.5, 2]

**Comment by aborruso** [comment]
Thank you very much, I will try it
